export default {
  TITLE_SUCCESS: "TITLE_SUCCESS",
  TOKEN_SUCESS: "TOKEN_SUCESS",
  USERID: "USERID",
  GET_USER_DATA: "GET_USER_DATA",
  LOGOUT: "LOGOUT",
  EMAIL: "EMAIL",
  SINGLE_TASK: "SINGLE_TASK",
  DELETE_S: "DELETE_S",
  SINGLE_KEY: "SINGLE_KEY",
};
